apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weather
  labels:
    name: weather
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        ##image: $DOCKER_REPO/weather:BUILD_NUMBER   ## uncomment this line when using jenkins build
        image: devopsahmed/weather:0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /version
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: OnFailure