apiVersion: v1
kind: Service
metadata:
  name: weather
  labels:
    service: weather
spec:
  selector:
    app: weather
  type: NodePort
  ports:
  - nodePort: 31127
    port: 5000
    protocol: TCP
    targetPort: 5000